version: "3.3"

services:
  traefik:
    image: traefik:v2.4.8
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web
    restart: always

  whoami:
    image: "containous/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    networks:
      - web

  psql_db:
    image: postgis/postgis:13-3.1
    container_name: "psql"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - psql_database
    volumes:
      - ./data:/var/lib/postgresql/data

  portainer:
    image: portainer/portainer-ce:2.6.1
    container_name: "portainer"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.localhost`)"
      - "traefik.http.routers.portainer.entrypoints=web"
      - 'traefik.http.services.portainer.loadbalancer.server.port=9000'
      - 'traefik.docker.network=web'
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    networks:
      - web

  db:
    image: mariadb:10.6.3
    container_name: "mariadb"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - mariadb_database
    volumes:
      - ./data:/var/lib/mysql

  mongodb:
    container_name: mongodb
    image: mongo:4.4.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mongodb-data:/data/db
    networks:
      - mongodb
    ports:
      - 27017:27017

  adminer:
    image: adminer:4.7.8
    container_name: "adminer"
    restart: "always"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer.localhost`)"
      - "traefik.http.routers.adminer.entrypoints=web"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
      - "traefik.docker.network=web"
    environment:
      - ADMINER_PLUGINS=tinymce
    volumes:
      - ./adminer/adminer.css:/var/www/html/adminer.css
      - ./adminer/login-password-less.php:/var/www/html/plugins-enabled/login-password-less.php
    networks:
      - mariadb_database
      - web
      - psql_database

volumes:
  portainer_data:

networks:
  web:
    name: web
  psql_database:
    name: psql_database
  mariadb_database:
    name: mariadb_database
  mongodb:
    name: mongodb