version: "3.3"

services:
  traefik:
    image: traefik:v2.4.8
    container_name: "traefik"
    restart: always
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=ibnumalikmy@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    # label:
    #   - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
    #   - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"
    #   - "traefik.http.routers.http_catchall.rule=HostRegexp(`{any:.+}`)"
    #   - "traefik.http.routers.http_catchall.entrypoints=web"
    #   - "traefik.http.routers.http_catchall.middlewares=https_redirect"

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`${WHOAMI_HOST}`)"
      - "traefik.http.routers.whoami.entrypoints=web,websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
    networks:
      - web

  psql_db:
    image: postgis/postgis:13-3.1
    container_name: "psql"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - psql_database
    volumes:
      - psql_data:/var/lib/postgresql/data

  portainer:
    image: portainer/portainer-ce:2.6.1
    container_name: "portainer"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.localhost`)"
      - "traefik.http.routers.portainer.entrypoints=web,websecure"
      - 'traefik.http.services.portainer.loadbalancer.server.port=9000'
      - 'traefik.docker.network=web'
      - "traefik.http.routers.portainer.tls.certresolver=myresolver"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - web

  db:
    image: mariadb:10.6.3
    container_name: "mariadb"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - mariadb_database
    volumes:
      - maria_data:/var/lib/mysql

  mongodb:
    container_name: mongodb
    image: mongo:4.4.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb
    ports:
      - 27017:27017

  adminer:
    image: adminer:4.8.1
    container_name: "adminer"
    restart: "always"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`${ADMINER_HOST}`)"
      - "traefik.http.routers.adminer.entrypoints=web,websecure"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
      - "traefik.docker.network=web"
      - "traefik.http.routers.adminer.tls.certresolver=myresolver"
    environment:
      - ADMINER_PLUGINS=tinymce
    volumes:
      - ./adminer/adminer.css:/var/www/html/adminer.css
      - ./adminer/login-password-less.php:/var/www/html/plugins-enabled/login-password-less.php
    networks:
      - mariadb_database
      - web
      - psql_database

  redis:
    image: redis:6.2.4
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/var/lib/redis
      # - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - web
      - redis

volumes:
  portainer_data:
    name: portainer_data
  psql_data:
    name: psql_data
  maria_data:
    name: maria_data
  mongodb_data:
    name: mongodb_data
  redis_data:
    name: redis_data

networks:
  web:
    name: web
  psql_database:
    name: psql_database
  mariadb_database:
    name: mariadb_database
  mongodb:
    name: mongodb
  redis:
    name: redis
